services:
  - type: web
    name: notenest
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
